USE dworks;

CREATE TABLE User (
	Id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	Name TEXT NOT NULL,
	Type INT(11) UNSIGNED NOT NULL,
	CreatedAt DATETIME NOT NULL DEFAULT NOW(),
	PRIMARY KEY(Id)
) engine = InnoDB;

CREATE TABLE  Project (
	Id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	Name VARCHAR(100) NOT NULL,
	UserId INT(11) UNSIGNED NOT NULL,
	CreatedAt DATETIME NOT NULL DEFAULT NOW(),
	PRIMARY KEY(Id)
) engine = InnoDB;

CREATE TABLE Task (
	Id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	CreatedAt DATETIME NOT NULL DEFAULT NOW(),
	Tittle VARCHAR(100) NOT NULL,
	Description VARCHAR(255) NOT NULL,
	Status INT(1) UNSIGNED NOT NULL,
	Priority INT(1) UNSIGNED NOT NULL,
	ProjectId INT(11) UNSIGNED NOT NULL,
	ExpiresAt DATETIME NOT NULL,
	PRIMARY KEY(Id)
) ENGINE = InnoDB;

CREATE TABLE Log (
	Id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	Entity VARCHAR(100) NOT NULL,
	EntityId INT(11) UNSIGNED NOT NULL,
	Operation VARCHAR(30) NOT NULL,	
	Field VARCHAR(100),
	Old VARCHAR(100),
	New VARCHAR(100) NOT NULL,
	Parent VARCHAR(100),
	ParentId INT(11) UNSIGNED,
	CreatedAt DATETIME NOT NULL DEFAULT NOW(),
	PRIMARY KEY(Id)
) ENGINE = InnoDB;

CREATE TABLE Comment (
	Id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	Content TEXT NOT NULL,
	TaskId INT(11) UNSIGNED NOT NULL,
	CreatedAt DATETIME NOT NULL DEFAULT NOW(),
	PRIMARY KEY(Id)
) ENGINE = InnoDB;

INSERT INTO `User` (Name, Type) VALUES
('User', 1),
('Manager', 2);