version: '3.8'
services:
  dworks:
    image: ${DOCKER_REGISTRY-}dworks
    container_name: apidworks
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - database
    ports:
      - "80:8080"
    restart: always
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development
  database:
    image: mysql:8.0.22
    cap_add:
      - SYS_NICE
    container_name: mysqldb
    ports:
      - "3306:3306"
    expose: 
      - 3306
    volumes:
      - db-vol-1:/var/lib/mysql
      - ./scripts/startup.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: p@ssword
      MYSQL_USER: dworksuser
      MYSQL_PASSWORD: p@ssword
      MYSQL_DATABASE: dworks
volumes:
  db-vol-1: